version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./backups:/app/backups
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
